/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author casto
 */
public class JAñadirUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JAñadirUsuario
     */
    public JAñadirUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        campoNombreUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNombreTarea = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 503, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 503, -1));

        campoNombreUsuario.setBackground(new java.awt.Color(51, 102, 255));
        campoNombreUsuario.setForeground(java.awt.Color.white);
        campoNombreUsuario.setBorder(null);
        campoNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(campoNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 503, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Nombre de la tarea:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        botonAñadir.setText("Añadir");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(botonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Añadir Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 932, 48));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Nombre de usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        campoNombreTarea.setBackground(new java.awt.Color(51, 102, 255));
        campoNombreTarea.setForeground(java.awt.Color.white);
        campoNombreTarea.setBorder(null);
        campoNombreTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreTareaActionPerformed(evt);
            }
        });
        jPanel1.add(campoNombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 503, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreTareaActionPerformed

    private void campoNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreUsuarioActionPerformed

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        String nombre_usuario = campoNombreUsuario.getText();
        String tarea = campoNombreTarea.getText();
        //creamos un usuario y una tarea dummy y dos boolean para comprobar recorriendo sus respectivas listas si existen
        Datos dat = Datos.cargarDatos();
        Usuario buscado = new Usuario("aa", "aa", "aa", "aa", "aa", "aa", "aa", "aa");
        String fechaEstandar = "0001/01/01";
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate FechaInicio = LocalDate.parse(fechaEstandar, formateador);
        Tarea buscada = new Tarea("", "", FechaInicio, FechaInicio, FechaInicio);
        boolean tareaEncontrada = false;
        boolean usuarioEncontrado = false;

        for (Usuario u : dat.getUsuarios()) {
            if (u.getNombre_usuario().equalsIgnoreCase(nombre_usuario)) {
                buscado = u;
                usuarioEncontrado = true;
            }
        }
        //usamos el usuario dummy para avisar si no existe el usuario instroducido
        if (buscado.getNombre_usuario().equals("aaaaaaaa")) {
            JOptionPane.showMessageDialog(this, "El usuario con el nombre de usuario Introducido no existe",
                    "Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
        }
        for (Tarea t : dat.getTareas()) {
            if (t.getTitulo().equalsIgnoreCase(tarea)) {
                buscada = t;
                tareaEncontrada = true;
            }
        }
        //usamos la tarea dummy para avisar al usuario de que la tarea introducida no existe
        if (buscada.getTitulo().equals("")) {
            JOptionPane.showMessageDialog(this, "La tarea no existe",
                    "error", JOptionPane.ERROR_MESSAGE);
        }
        //si tanto la tarea como el usuario existen se añaden cada uno a sus respectivas listas
        if (tareaEncontrada && usuarioEncontrado) {
            buscada.añadirUsuario(buscado);
            buscado.añadirTarea(buscada);
            Datos.guardarDatos(dat);
            JOptionPane.showMessageDialog(this, "El usuario " + buscado.getNombre_usuario() + " ha sido añadido a la tarea " + buscada.getTitulo(),
                    "Exitos", JOptionPane.INFORMATION_MESSAGE);
        }
        campoNombreTarea.setText("");
        campoNombreUsuario.setText("");
    }//GEN-LAST:event_botonAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAñadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAñadirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadir;
    private javax.swing.JTextField campoNombreTarea;
    private javax.swing.JTextField campoNombreUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
