/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Carri
 */
public class JAñadirTarea extends javax.swing.JFrame {

    /**
     * Creates new form JAñadirTarea
     */
    public JAñadirTarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        botonAñadir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNombreProyecto = new javax.swing.JTextField();
        campoNombreTituloTarea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 580, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 580, -1));

        botonAñadir.setText("Añadir");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(botonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Titulo tarea:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Nombre proyecto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        campoNombreProyecto.setBackground(new java.awt.Color(51, 102, 255));
        campoNombreProyecto.setForeground(java.awt.Color.white);
        campoNombreProyecto.setBorder(null);
        jPanel1.add(campoNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 580, -1));

        campoNombreTituloTarea.setBackground(new java.awt.Color(51, 102, 255));
        campoNombreTituloTarea.setForeground(java.awt.Color.white);
        campoNombreTituloTarea.setBorder(null);
        jPanel1.add(campoNombreTituloTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 580, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Añadir tarea");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 73));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        String proyecto = campoNombreProyecto.getText();
        String tarea = campoNombreTituloTarea.getText();
        //Creamos un proyecto y una tarea dummy y dos boolean para comprobar si existen los datos introducidos por el usuario
        Datos dat = Datos.cargarDatos();
        String fechaEstandar = "0001/01/01";
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate FechaInicio = LocalDate.parse(fechaEstandar, formateador);
        Proyecto buscado = new Proyecto("", FechaInicio, FechaInicio);
        Tarea buscada = new Tarea("", "", FechaInicio, FechaInicio, FechaInicio);
        boolean tareaEncontrada = false;
        boolean proyectoEncontrado = false;

        for (Proyecto p : dat.getProyectos()) {
            if (p.getNombre().equalsIgnoreCase(proyecto)) {
                buscado = p;
                proyectoEncontrado = true;
            }
        }
        //si el proyecto no existe se le avisa al usuario
        if (buscado.getNombre().equals("")) {
            JOptionPane.showMessageDialog(this, "El proyecto con el nombre introducido no existe",
                    "Proyecto no encontrado", JOptionPane.ERROR_MESSAGE);
        }
        for (Tarea t : dat.getTareas()) {
            if (t.getTitulo().equalsIgnoreCase(tarea)) {
                buscada = t;
                tareaEncontrada = true;
            }
        }
        //si la tarea no existe se le avisa al usuario
        if (buscada.getTitulo().equals("")) {
            JOptionPane.showMessageDialog(this, "La tarea no existe",
                    "error", JOptionPane.ERROR_MESSAGE);
        }
        //si ambos existe se añaden a sus listas respectivamente
        if (tareaEncontrada && proyectoEncontrado) {
            buscado.añadirTarea(buscada);
            buscada.setEnProyecto(true);
            Datos.guardarDatos(dat);
            JOptionPane.showMessageDialog(this, "La tarea " + buscada.getTitulo()+ " ha sido añadida al proyecto " + buscado.getNombre(),
                    "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
        
        campoNombreProyecto.setText("");
        campoNombreTituloTarea.setText("");
    }//GEN-LAST:event_botonAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAñadirTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAñadirTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAñadirTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAñadirTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAñadirTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadir;
    private javax.swing.JTextField campoNombreProyecto;
    private javax.swing.JTextField campoNombreTituloTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
