/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Carri
 */
public class JBuscarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JBuscarUsuario
     */
    public JBuscarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        campoSexo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoNombreUsuarioBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoApellido1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        campoDNI = new javax.swing.JTextField();
        campoApellido2 = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 411, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 411, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 410, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 411, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 411, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 411, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 411, 10));

        campoSexo.setBackground(new java.awt.Color(51, 102, 255));
        campoSexo.setForeground(java.awt.Color.white);
        campoSexo.setBorder(null);
        jPanel1.add(campoSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 411, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Nombre:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, 31));

        campoNombreUsuarioBuscar.setBackground(new java.awt.Color(51, 102, 255));
        campoNombreUsuarioBuscar.setForeground(java.awt.Color.white);
        campoNombreUsuarioBuscar.setBorder(null);
        jPanel1.add(campoNombreUsuarioBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 411, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 856, 55));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Direccion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre de usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        campoApellido1.setBackground(new java.awt.Color(51, 102, 255));
        campoApellido1.setForeground(java.awt.Color.white);
        campoApellido1.setBorder(null);
        jPanel1.add(campoApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 411, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Segundo apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, 31));

        botonEliminar.setText("Buscar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        campoDNI.setBackground(new java.awt.Color(51, 102, 255));
        campoDNI.setForeground(java.awt.Color.white);
        campoDNI.setBorder(null);
        jPanel1.add(campoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 411, -1));

        campoApellido2.setBackground(new java.awt.Color(51, 102, 255));
        campoApellido2.setForeground(java.awt.Color.white);
        campoApellido2.setBorder(null);
        jPanel1.add(campoApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 411, -1));

        campoNombre.setBackground(new java.awt.Color(51, 102, 255));
        campoNombre.setForeground(java.awt.Color.white);
        campoNombre.setBorder(null);
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 411, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Primer apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, 31));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Sexo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, 31));

        campoDireccion.setBackground(new java.awt.Color(51, 102, 255));
        campoDireccion.setForeground(java.awt.Color.white);
        campoDireccion.setBorder(null);
        jPanel1.add(campoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 411, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("DNI:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        String nombreUsuarioBuscar = campoNombreUsuarioBuscar.getText();

        Datos dat = Datos.cargarDatos();
        //creamos un Usuario dummy y comprobamos si existe el nombre de usuario introducido
        Usuario buscado = new Usuario("aa", "aa", "aa", "aa", "aa", "aa", "aa", "aa");
        for (Usuario u : dat.getUsuarios()) {
            if (u.getNombre_usuario().equalsIgnoreCase(nombreUsuarioBuscar)) {
                buscado = u;
            }
        }
        //usamos el usuario dummy para avisar al usuario si no existe el suuario introducido
        //si existe rpocede a cargar los datos
        if (buscado.getNombre_usuario().equals("aaaaaaaa")) {
            JOptionPane.showMessageDialog(this, "El usuario no existe",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            campoNombre.setText(buscado.getNombre());
            campoApellido1.setText(buscado.getApellido1());
            campoApellido2.setText(buscado.getApellido2());
            campoDNI.setText(buscado.getDNI());
            campoDireccion.setText(buscado.getDireccion());
            campoSexo.setText(buscado.getSexo());
        }
        campoNombreUsuarioBuscar.setText("");
    }//GEN-LAST:event_botonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JBuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JBuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JBuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JBuscarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JBuscarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JTextField campoApellido1;
    private javax.swing.JTextField campoApellido2;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNombreUsuarioBuscar;
    private javax.swing.JTextField campoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
