/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author casto
 */
public class JCrearTarea extends javax.swing.JFrame {

    /**
     * Creates new form JCrearTarea
     */
    public JCrearTarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoFechaInicio = new javax.swing.JFormattedTextField();
        campoFechaEstimada = new javax.swing.JFormattedTextField();
        campoFechaFin = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        campoUsuarioPrincipal = new javax.swing.JTextField();
        campoTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDescripcion = new javax.swing.JTextArea();
        botonCrearTarea = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 650, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 650, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear tarea");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 845, 56));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Fecha inicio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Fecha finalizacion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Descripción:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        campoFechaInicio.setBackground(new java.awt.Color(51, 102, 255));
        campoFechaInicio.setForeground(java.awt.Color.white);
        campoFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        campoFechaInicio.setText("yyyy/MM/dd");
        campoFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaInicioActionPerformed(evt);
            }
        });
        jPanel1.add(campoFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 650, -1));

        campoFechaEstimada.setBackground(new java.awt.Color(51, 102, 255));
        campoFechaEstimada.setForeground(java.awt.Color.white);
        campoFechaEstimada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        campoFechaEstimada.setText("yyyy/MM/dd");
        jPanel1.add(campoFechaEstimada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 650, -1));

        campoFechaFin.setBackground(new java.awt.Color(51, 102, 255));
        campoFechaFin.setForeground(java.awt.Color.white);
        campoFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        campoFechaFin.setText("yyyy/MM/dd");
        jPanel1.add(campoFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 650, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Fecha estimada:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        campoUsuarioPrincipal.setBackground(new java.awt.Color(51, 102, 255));
        campoUsuarioPrincipal.setForeground(java.awt.Color.white);
        campoUsuarioPrincipal.setBorder(null);
        jPanel1.add(campoUsuarioPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 650, -1));

        campoTitulo.setBackground(new java.awt.Color(51, 102, 255));
        campoTitulo.setForeground(java.awt.Color.white);
        campoTitulo.setBorder(null);
        campoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTituloActionPerformed(evt);
            }
        });
        jPanel1.add(campoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 650, -1));

        areaDescripcion.setBackground(new java.awt.Color(51, 102, 255));
        areaDescripcion.setColumns(20);
        areaDescripcion.setForeground(java.awt.Color.white);
        areaDescripcion.setRows(5);
        jScrollPane1.setViewportView(areaDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 650, -1));

        botonCrearTarea.setText("Crear");
        botonCrearTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearTareaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Título:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 50, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Usuario principal:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloActionPerformed

    private void botonCrearTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearTareaActionPerformed
        //Inicializamos una variables que nos haran falta mas tarde
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate FechaInicio = LocalDate.parse(campoFechaInicio.getText(), formateador);
        LocalDate FechaEstimada = LocalDate.parse(campoFechaEstimada.getText(), formateador);
        LocalDate FechaFin = LocalDate.parse(campoFechaFin.getText(), formateador);
        Datos dat = Datos.cargarDatos();
        //Creamos un usuario dummy y un boolean para comprobar si existe
        String nombreUsuario = campoUsuarioPrincipal.getText();
        boolean encontrado = false;
        Usuario usuarioEncontrado = new Usuario("aa", "aa", "aa", "aa", "aa", "aa", "aa", "aa");
        for (Usuario us : dat.getUsuarios()) {
            if (nombreUsuario.equalsIgnoreCase(us.getNombre_usuario())) {
                usuarioEncontrado = us;
                encontrado = true;
            }
        }
        //si se encuentra pasamos a la creacion de una tarea
        if (encontrado) {
            Tarea t = new Tarea(campoTitulo.getText(), areaDescripcion.getText(), FechaInicio,
                    FechaEstimada, FechaFin);
            //Comprobamos si el titulo de la tarea ya existe para que no se repitan
            //Creamos una cadena con todos los titulos de todas las tareas y comprobamos si el titulo nuevo introducido
            //se encuentra en esta cadena creada  
            String cadenatitulos = "";
            for (Tarea ts : dat.getTareas()) {
                cadenatitulos += ts.getTitulo();
            }
            //si se encuentra una coincidencia se avisa al usuario, si no se crea la tarea
            if (cadenatitulos.contains(t.getTitulo())) {
                JOptionPane.showMessageDialog(this, "Ese titulo de tarea ya existe.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                dat.añadirTarea(t);
                t.añadirUsuario(usuarioEncontrado);
                Datos.guardarDatos(dat);
                usuarioEncontrado.añadirTarea(t);
                Datos.guardarDatos(dat);

                JOptionPane.showMessageDialog(this, "Tarea creada con éxito", "Guardado correctamente",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        }
        //si no se encuentra un usuario se avisa al usuario
        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado, inserte un usuario existente", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        campoFechaEstimada.setText("");
        campoFechaFin.setText("");
        campoFechaInicio.setText("");
        campoTitulo.setText("");
        campoUsuarioPrincipal.setText("");
        areaDescripcion.setText("");
    }//GEN-LAST:event_botonCrearTareaActionPerformed

    private void campoFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCrearTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCrearTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescripcion;
    private javax.swing.JButton botonCrearTarea;
    private javax.swing.JFormattedTextField campoFechaEstimada;
    private javax.swing.JFormattedTextField campoFechaFin;
    private javax.swing.JFormattedTextField campoFechaInicio;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JTextField campoUsuarioPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
