/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Carri
 */
public class JCrearUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form JCrearUsuarios
     */
    public JCrearUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoFraseSeguridad = new javax.swing.JTextField();
        campoDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botonCrearUsuario = new javax.swing.JButton();
        campoApellido1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoApellido2 = new javax.swing.JTextField();
        campoDNI = new javax.swing.JTextField();
        campoSexo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoContraseña = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 130, 740, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 130, 740, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 740, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 751, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 751, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 751, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 751, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 751, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 751, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Contraseña:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Sexo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, 30));

        campoFraseSeguridad.setBackground(new java.awt.Color(51, 102, 255));
        campoFraseSeguridad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoFraseSeguridad.setForeground(java.awt.Color.white);
        campoFraseSeguridad.setBorder(null);
        campoFraseSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFraseSeguridadActionPerformed(evt);
            }
        });
        jPanel1.add(campoFraseSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 751, -1));

        campoDireccion.setBackground(new java.awt.Color(51, 102, 255));
        campoDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoDireccion.setForeground(java.awt.Color.white);
        campoDireccion.setBorder(null);
        campoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(campoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 751, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("DNI:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 30));

        botonCrearUsuario.setText("Crear usuario");
        botonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 180, 50));

        campoApellido1.setBackground(new java.awt.Color(51, 102, 255));
        campoApellido1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoApellido1.setForeground(java.awt.Color.white);
        campoApellido1.setBorder(null);
        campoApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellido1ActionPerformed(evt);
            }
        });
        jPanel1.add(campoApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 751, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Frase de seguridad:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Segundo apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 30));

        campoNombre.setBackground(new java.awt.Color(51, 102, 255));
        campoNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoNombre.setForeground(java.awt.Color.white);
        campoNombre.setBorder(null);
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 751, -1));

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 994, 56));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 30));

        campoApellido2.setBackground(new java.awt.Color(51, 102, 255));
        campoApellido2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoApellido2.setForeground(java.awt.Color.white);
        campoApellido2.setBorder(null);
        campoApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellido2ActionPerformed(evt);
            }
        });
        jPanel1.add(campoApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 751, -1));

        campoDNI.setBackground(new java.awt.Color(51, 102, 255));
        campoDNI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoDNI.setForeground(java.awt.Color.white);
        campoDNI.setBorder(null);
        campoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDNIActionPerformed(evt);
            }
        });
        jPanel1.add(campoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 751, -1));

        campoSexo.setBackground(new java.awt.Color(51, 102, 255));
        campoSexo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoSexo.setForeground(java.awt.Color.white);
        campoSexo.setBorder(null);
        campoSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSexoActionPerformed(evt);
            }
        });
        jPanel1.add(campoSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 751, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Primer apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 30));

        campoContraseña.setBackground(new java.awt.Color(51, 102, 255));
        campoContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campoContraseña.setForeground(java.awt.Color.white);
        campoContraseña.setBorder(null);
        campoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(campoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 751, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Direccion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellido1ActionPerformed

    private void campoApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellido2ActionPerformed

    private void campoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionActionPerformed

    private void campoSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSexoActionPerformed

    private void campoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDNIActionPerformed

    private void campoFraseSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFraseSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFraseSeguridadActionPerformed

    private void campoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContraseñaActionPerformed

    private void botonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearUsuarioActionPerformed
        //comprobamos que los 4 primeros campos tengan una longitus de 2 caracteres como minimo
        //si cumple la condicion se crea un usuario con los parametro introducidos y se avisa al usuario con
        //su nombre de usuario creado
        if (campoNombre.getText().length() < 2 || campoApellido1.getText().length() < 2
                || campoApellido2.getText().length() < 2 || campoDNI.getText().length() < 2) {
            JOptionPane.showMessageDialog(this, "Los campos nombre, apellidos y DNI deben tener al menos de 2 caracteres", "Error fatal",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            Usuario u = new Usuario(campoNombre.getText(), campoApellido1.getText(),
                    campoApellido2.getText(), campoDNI.getText(), campoDireccion.getText(),
                    campoSexo.getText(), campoContraseña.getText(), campoFraseSeguridad.getText());
            Datos dat = Datos.cargarDatos();
            dat.añadirUsuario(u);
            Datos.guardarDatos(dat);
            JOptionPane.showMessageDialog(this, "Tu nombre de usuario es: " + u.getNombre_usuario(), "Guardado correctamente",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        campoNombre.setText("");
        campoApellido1.setText("");
        campoApellido2.setText("");
        campoDNI.setText("");
        campoDireccion.setText("");
        campoSexo.setText("");
        campoContraseña.setText("");
        campoFraseSeguridad.setText("");

    }//GEN-LAST:event_botonCrearUsuarioActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCrearUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearUsuario;
    private javax.swing.JTextField campoApellido1;
    private javax.swing.JTextField campoApellido2;
    private javax.swing.JTextField campoContraseña;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoFraseSeguridad;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
