/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Carri
 */
public class JEditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JEditarUsuario
     */
    public JEditarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoNombreUsuario = new javax.swing.JTextField();
        botonBuscarTareas = new javax.swing.JButton();
        campoApellido1 = new javax.swing.JTextField();
        campoApellido2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoSexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botonGuardarCambios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre de usuario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        campoNombreUsuario.setBackground(new java.awt.Color(51, 102, 255));
        campoNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        campoNombreUsuario.setBorder(null);
        campoNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(campoNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 380, -1));

        botonBuscarTareas.setText("Buscar");
        botonBuscarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarTareasActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        campoApellido1.setBackground(new java.awt.Color(51, 102, 255));
        campoApellido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoApellido1.setForeground(new java.awt.Color(255, 255, 255));
        campoApellido1.setBorder(null);
        campoApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellido1ActionPerformed(evt);
            }
        });
        jPanel1.add(campoApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 380, -1));

        campoApellido2.setBackground(new java.awt.Color(51, 102, 255));
        campoApellido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoApellido2.setForeground(new java.awt.Color(255, 255, 255));
        campoApellido2.setBorder(null);
        campoApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellido2ActionPerformed(evt);
            }
        });
        jPanel1.add(campoApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 380, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Direccion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        campoNombre.setBackground(new java.awt.Color(51, 102, 255));
        campoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(255, 255, 255));
        campoNombre.setBorder(null);
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 380, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sexo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        campoDireccion.setBackground(new java.awt.Color(51, 102, 255));
        campoDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoDireccion.setForeground(new java.awt.Color(255, 255, 255));
        campoDireccion.setBorder(null);
        campoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(campoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 380, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Primer apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        campoSexo.setBackground(new java.awt.Color(51, 102, 255));
        campoSexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoSexo.setForeground(new java.awt.Color(255, 255, 255));
        campoSexo.setBorder(null);
        campoSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSexoActionPerformed(evt);
            }
        });
        jPanel1.add(campoSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 380, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Segundo apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        campoDNI.setBackground(new java.awt.Color(51, 102, 255));
        campoDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoDNI.setForeground(new java.awt.Color(255, 255, 255));
        campoDNI.setBorder(null);
        campoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDNIActionPerformed(evt);
            }
        });
        jPanel1.add(campoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 380, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        botonGuardarCambios.setText("Guardar");
        botonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarCambiosActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 380, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 380, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 380, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 380, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 380, -1));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 380, -1));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreUsuarioActionPerformed

    private void campoApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellido1ActionPerformed

    private void campoApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellido2ActionPerformed

    private void campoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDireccionActionPerformed

    private void campoSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSexoActionPerformed

    private void campoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDNIActionPerformed

    private void botonBuscarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarTareasActionPerformed
        String nombre_usuario = campoNombreUsuario.getText();
        //con un Usuario dummy recorremos la lista de Usuarios y comprobamos si existe
        Datos dat = Datos.cargarDatos();
        Usuario buscado = new Usuario("aa", "aa", "aa", "aa", "aa", "aa", "aa", "aa");
        for (Usuario u : dat.getUsuarios()) {
            if (u.getNombre_usuario().equalsIgnoreCase(nombre_usuario)) {
                buscado = u;
            }
        }
        //si no existe se advierte al usuario y si existe se cargan los datos en sus campos correspondientes para modificar
        if (buscado.getNombre_usuario().equals("aaaaaaaa")) {
            JOptionPane.showMessageDialog(this, "El usuario con el nombre de usuario Introducido no existe",
                    "Usuario no encontrado", JOptionPane.WARNING_MESSAGE);
        } else {
            campoNombre.setText(buscado.getNombre());
            campoApellido1.setText(buscado.getApellido1());
            campoApellido2.setText(buscado.getApellido2());
            campoDNI.setText(buscado.getDNI());
            campoDireccion.setText(buscado.getDireccion());
            campoNombreUsuario.setText(buscado.getNombre_usuario());
            campoSexo.setText(buscado.getSexo());
        }
        

    }//GEN-LAST:event_botonBuscarTareasActionPerformed

    private void botonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCambiosActionPerformed
        String nombre_usuario = campoNombreUsuario.getText();
        Datos datos = Datos.cargarDatos();
        Usuario buscado = new Usuario("aa", "aa", "aa", "aa", "aa", "aa", "aa", "aa");
        //volvemos a cargar el usuario introducido
        for (Usuario u : datos.getUsuarios()) {
            if (u.getNombre_usuario().equalsIgnoreCase(nombre_usuario)) {
                buscado = u;
            }
        }
        if (buscado.getNombre_usuario().equals("aaaaaaaa")) {
            JOptionPane.showMessageDialog(this, "El usuario con el nombre de usuario Introducido no existe",
                    "Usuario no encontrado", JOptionPane.WARNING_MESSAGE);
        } else if (campoNombre.getText().length() < 2 || campoApellido1.getText().length() < 2
                || campoApellido2.getText().length() < 2 || campoDNI.getText().length() < 2) {
            JOptionPane.showMessageDialog(this, "Los campos nombre, apellidos y DNI deben tener al menos de 2 caracteres", "Error fatal",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            //cambiamos los campos introducidos por el usuario en el usuario de la lista de Usuarios
            buscado.setNombre(campoNombre.getText());
            buscado.setApellido1(campoApellido1.getText());
            buscado.setApellido2(campoApellido2.getText());
            buscado.setDNI(campoDNI.getText());
            buscado.setDireccion(campoDireccion.getText());
            buscado.setSexo(campoSexo.getText());
            String parteNombre = campoNombre.getText().substring(0, 2);
            String parteApellido1 = campoApellido1.getText().substring(0, 2);
            String parteApellido2 = campoApellido2.getText().substring(0, 2);
            String parteDNI = campoDNI.getText().substring(0, 2);
            buscado.setNombre_usuario(parteNombre + parteApellido1 + parteApellido2 + parteDNI);
            Datos.guardarDatos(datos);
            JOptionPane.showMessageDialog(this, "El usaurio ha sido modificado exitosamente, su nuevo nombre de usuarios es" + buscado.getNombre_usuario() +".",
                    "Modificado con exito", JOptionPane.INFORMATION_MESSAGE);
        }
        
        campoApellido1.setText("");
        campoApellido2.setText("");
        campoDNI.setText("");
        campoDireccion.setText("");
        campoNombre.setText("");
        campoNombreUsuario.setText("");
        campoSexo.setText("");
    }//GEN-LAST:event_botonGuardarCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JEditarUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JEditarUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JEditarUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JEditarUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JEditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarTareas;
    private javax.swing.JButton botonGuardarCambios;
    private javax.swing.JTextField campoApellido1;
    private javax.swing.JTextField campoApellido2;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNombreUsuario;
    private javax.swing.JTextField campoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
