/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Carri
 */
public class JEditarProyecto extends javax.swing.JFrame {

    /**
     * Creates new form JEditarProyecto
     */
    public JEditarProyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        campoTituloBuscar = new javax.swing.JTextField();
        campoTituloEditar = new javax.swing.JTextField();
        campoFechaComienzo = new javax.swing.JFormattedTextField();
        campoFechaFin = new javax.swing.JFormattedTextField();
        botonBuscar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 127, 557, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Titulo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Fecha comienzo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 244, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Fecha fin:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 288, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 557, 10));

        campoTituloBuscar.setBackground(new java.awt.Color(51, 102, 255));
        campoTituloBuscar.setForeground(java.awt.Color.white);
        campoTituloBuscar.setBorder(null);
        jPanel1.add(campoTituloBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 557, -1));

        campoTituloEditar.setBackground(new java.awt.Color(51, 102, 255));
        campoTituloEditar.setForeground(java.awt.Color.white);
        campoTituloEditar.setBorder(null);
        jPanel1.add(campoTituloEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 557, 20));

        campoFechaComienzo.setBackground(new java.awt.Color(51, 102, 255));
        campoFechaComienzo.setForeground(java.awt.Color.white);
        campoFechaComienzo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        campoFechaComienzo.setText("yyyy/MM/dd");
        campoFechaComienzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaComienzoActionPerformed(evt);
            }
        });
        jPanel1.add(campoFechaComienzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 248, 557, -1));

        campoFechaFin.setBackground(new java.awt.Color(51, 102, 255));
        campoFechaFin.setForeground(java.awt.Color.white);
        campoFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        campoFechaFin.setText("yyyy/MM/dd");
        jPanel1.add(campoFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 292, 557, -1));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 148, -1, -1));

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 332, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar proyecto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 56));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Titulo del proyecto a editar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 104, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        String nombreProyectoBuscar = campoTituloBuscar.getText();

        Datos dat = Datos.cargarDatos();
        String fechaEstandar = "0001/01/01";
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate FechaInicio = LocalDate.parse(fechaEstandar, formateador);
        //volvamos a cargar el pryecto en cuestion
        Proyecto buscado = new Proyecto("", FechaInicio, FechaInicio);
        for (Proyecto p : dat.getProyectos()) {
            if (p.getNombre().equalsIgnoreCase(nombreProyectoBuscar)) {
                buscado = p;
            }
            //modificamos los atributos del proyecto dependiendo de los datos introducidos por el usuario
        }
        if (buscado.getNombre().equals("")) {
            JOptionPane.showMessageDialog(this, "El proyecto con el titulo introducido no existe.",
                "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            //transformamos los String de fecha introducidos a LocalDate para que puedan ser instroducidos al Proyecto
            LocalDate fechaInicio = LocalDate.parse(campoFechaComienzo.getText(), formateador);
            LocalDate fechaFin = LocalDate.parse(campoFechaFin.getText(), formateador);
            //Para comprobar que no exista otro proyecto con el mismo Titulo creamos una cadena de String
            //con todos los nombres de los proyectos y miramos si existe alguna coincidencia con el titulo
            //introducido por el usuraio
            String cadenatitulos = "";
            for (Proyecto ps : dat.getProyectos()) {
                cadenatitulos += ps.getNombre();
            }
            //si existe coincidencia se avisa al usuario y se guardan el resto de las modificaciones
            if (cadenatitulos.contains(campoTituloEditar.getText())) {
                JOptionPane.showMessageDialog(this, "Ese titulo de proyecto ya existe.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            } else {
                buscado.setNombre(campoTituloEditar.getText());
            }
            buscado.setFecha_inicio(fechaInicio);
            buscado.setFecha_entrega(fechaFin);
            JOptionPane.showMessageDialog(this, "Proyecto editado con exito", "exito",
                    JOptionPane.INFORMATION_MESSAGE);

        }
        Datos.guardarDatos(dat);
        campoFechaComienzo.setText("");
        campoFechaFin.setText("");
        campoTituloBuscar.setText("");
        campoTituloEditar.setText("");
        
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        //Cargamos datos e inicializamos variables que nos haran falta
        Datos dat = Datos.cargarDatos();
        DefaultListModel modeloLista = new DefaultListModel();
        String nombreproyecto = campoTituloBuscar.getText();
        String fechaEstandar = "0001/01/01";
        //para trabajar con un formato de fecha entendible
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate FechaInicio = LocalDate.parse(fechaEstandar, formateador);
        //creamos un proyecto dummy y buscamos en la lista un proyecto que coincida con el nombre que nos introduce el usuario
        Proyecto p = new Proyecto("", FechaInicio, FechaInicio);
        for (Proyecto pro : dat.getProyectos()) {
            if (pro.getNombre().equalsIgnoreCase(nombreproyecto)) {
                p = pro;
            }
        }
        //si no encuentra coincidencias ustilizamos el proyecto dummy para mandar un mensaje de alerta al usuario
        //si encuentra una coincidencia entonces mostramos en la lista los datos
        if (p.getNombre().equals("")) {
            JOptionPane.showMessageDialog(this, "El Proyecto con el nombre Introducido no existe",
                    "error", JOptionPane.ERROR_MESSAGE);
        } else {
            campoTituloEditar.setText(p.getNombre());
            campoFechaComienzo.setText(p.getFecha_inicio().format(formateador));
            campoFechaFin.setText(p.getFecha_entrega().format(formateador));
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void campoFechaComienzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaComienzoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaComienzoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JEditarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JEditarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JEditarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JEditarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JEditarProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JFormattedTextField campoFechaComienzo;
    private javax.swing.JFormattedTextField campoFechaFin;
    private javax.swing.JTextField campoTituloBuscar;
    private javax.swing.JTextField campoTituloEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
