/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Carri
 */
public class JEditarTarea extends javax.swing.JFrame {

    /**
     * Creates new form JEditarTarea
     */
    public JEditarTarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoFechaFin = new javax.swing.JFormattedTextField();
        campoTareaBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDescripcion = new javax.swing.JTextArea();
        campoTituloTareaEditar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        botonEditar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        campoFechaEstimada = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoFechaInicio = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoFechaFin.setBackground(new java.awt.Color(51, 102, 255));
        campoFechaFin.setForeground(new java.awt.Color(255, 255, 255));
        campoFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        campoFechaFin.setText("yyyy/MM/dd");
        campoFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaFinActionPerformed(evt);
            }
        });
        jPanel1.add(campoFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 560, -1));

        campoTareaBuscar.setBackground(new java.awt.Color(51, 102, 255));
        campoTareaBuscar.setForeground(new java.awt.Color(255, 255, 255));
        campoTareaBuscar.setBorder(null);
        jPanel1.add(campoTareaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 560, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Título de la tarea a editar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Fecha fin:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Fecha incio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        areaDescripcion.setBackground(new java.awt.Color(51, 102, 255));
        areaDescripcion.setColumns(20);
        areaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        areaDescripcion.setRows(5);
        areaDescripcion.setBorder(null);
        jScrollPane1.setViewportView(areaDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 560, 111));

        campoTituloTareaEditar.setBackground(new java.awt.Color(51, 102, 255));
        campoTituloTareaEditar.setForeground(new java.awt.Color(255, 255, 255));
        campoTituloTareaEditar.setBorder(null);
        jPanel1.add(campoTituloTareaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 560, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Titulo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        campoFechaEstimada.setBackground(new java.awt.Color(51, 102, 255));
        campoFechaEstimada.setForeground(new java.awt.Color(255, 255, 255));
        campoFechaEstimada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        campoFechaEstimada.setText("yyyy/MM/dd");
        jPanel1.add(campoFechaEstimada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 560, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar tarea");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 56));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Descripción:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        campoFechaInicio.setBackground(new java.awt.Color(51, 102, 255));
        campoFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        campoFechaInicio.setText("yyyy/MM/dd");
        jPanel1.add(campoFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 560, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Fecha estimada:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 560, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 560, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 560, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 560, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 560, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 560, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 560, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 560, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 560, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String nombreTareaBuscar = campoTareaBuscar.getText();

        Datos dat = Datos.cargarDatos();
        String fechaEstandar = "0001/01/01";
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate FechaInicio = LocalDate.parse(fechaEstandar, formateador);
        //buscamos si la tarea que nos ha introducido el usuario existe y la cargamos
        Tarea buscada = new Tarea("", "", FechaInicio, FechaInicio, FechaInicio);
        for (Tarea t : dat.getTareas()) {
            if (t.getTitulo().equalsIgnoreCase(nombreTareaBuscar)) {
                buscada = t;
            }
        }
        //informamos al usuario si no existe dicha tarea
        //si existe cargamos los datos en sus campos para modificar
        if (buscada.getTitulo().equals("")) {
            JOptionPane.showMessageDialog(this, "La tarea con el titulo introducido no existe.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            campoTituloTareaEditar.setText(buscada.getTitulo());
            campoFechaInicio.setText(buscada.getFecha_inicio().format(formateador));
            campoFechaEstimada.setText(buscada.getFecha_estimada().format(formateador));
            campoFechaFin.setText(buscada.getFecha_fin().format(formateador));
            areaDescripcion.setText(buscada.getDescripcion());
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        String nombreTareaBuscar = campoTareaBuscar.getText();

        Datos dat = Datos.cargarDatos();
        String fechaEstandar = "0001/01/01";
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate FechaInicio = LocalDate.parse(fechaEstandar, formateador);
        //cargamos la tarea que nos introduce el usuario de nuevo
        Tarea buscada = new Tarea("", "", FechaInicio, FechaInicio, FechaInicio);
        for (Tarea t : dat.getTareas()) {
            if (t.getTitulo().equalsIgnoreCase(nombreTareaBuscar)) {
                buscada = t;
            }
        }
        if (buscada.getTitulo().equals("")) {
            JOptionPane.showMessageDialog(this, "La tarea con el titulo introducido no existe.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            //cambiamos los Strings de las fechas a tipo LocalDate para que pueden ser introducidos
            LocalDate fechaInicio = LocalDate.parse(campoFechaInicio.getText(), formateador);
            LocalDate fechaEstimada = LocalDate.parse(campoFechaEstimada.getText(), formateador);
            LocalDate fechaFin = LocalDate.parse(campoFechaFin.getText(), formateador);
            //Comprobamos si el titulo de la tarea ya existe para que no se repitan
            //Creamos una cadena con todos los titulos de todas las tareas y comprobamos si el titulo nuevo introducido
            //se encuentra en esta cadena creada            
            String cadenatitulos = "";
            for (Tarea ts : dat.getTareas()) {
                cadenatitulos += ts.getTitulo();
            }
            //Si ya existe este titulo no se modificara el titulo pero si el resto de datos
            if (cadenatitulos.contains(campoTituloTareaEditar.getText())) {
                JOptionPane.showMessageDialog(this, "Ese titulo de tarea ya existe.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                buscada.setTitulo(campoTituloTareaEditar.getText());
            }
            buscada.setFecha_inicio(fechaInicio);
            buscada.setFecha_estimada(fechaEstimada);
            buscada.setFecha_fin(fechaFin);
            buscada.setDescripcion(areaDescripcion.getText());
            JOptionPane.showMessageDialog(this, "Tarea editada con exito", "teamo amieva",
                    JOptionPane.INFORMATION_MESSAGE);

        }
        Datos.guardarDatos(dat);
        campoFechaEstimada.setText("");
        campoFechaFin.setText("");
        campoFechaInicio.setText("");
        campoTareaBuscar.setText("");
        campoTituloTareaEditar.setText("");
        areaDescripcion.setText("");
    }//GEN-LAST:event_botonEditarActionPerformed

    private void campoFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaFinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JEditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JEditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JEditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JEditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JEditarTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescripcion;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JFormattedTextField campoFechaEstimada;
    private javax.swing.JFormattedTextField campoFechaFin;
    private javax.swing.JFormattedTextField campoFechaInicio;
    private javax.swing.JTextField campoTareaBuscar;
    private javax.swing.JTextField campoTituloTareaEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
