/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author casto
 */
public class JEliminarTarea extends javax.swing.JFrame {

    /**
     * Creates new form JEliminarTarea
     */
    public JEliminarTarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNombreTarea = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar tarea");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de la tarea");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        campoNombreTarea.setBackground(new java.awt.Color(0, 102, 255));
        campoNombreTarea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNombreTarea.setForeground(new java.awt.Color(255, 255, 255));
        campoNombreTarea.setBorder(null);
        campoNombreTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreTareaActionPerformed(evt);
            }
        });
        jPanel1.add(campoNombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 350, -1));

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreTareaActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        String nombreTarea = campoNombreTarea.getText();

        Datos dat = Datos.cargarDatos();
        String fechaEstandar = "0001/01/01";
        //creamos un formateador de fecha para que sesa legible
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate FechaInicio = LocalDate.parse(fechaEstandar, formateador);
        //tarea dummy 
        Tarea tareaestandar = new Tarea("", "", FechaInicio, FechaInicio, FechaInicio);
        //recorremos tareas para ver si existe la tarea introducida
        for (Tarea t : dat.getTareas()) {
            if (t.getTitulo().equalsIgnoreCase(nombreTarea)) {
                tareaestandar = t;
                JOptionPane.showMessageDialog(this, "La tarea " + nombreTarea + "ha sido eliminada con exito",
                        "Tarea eliminada", JOptionPane.INFORMATION_MESSAGE);
            }   
        }
        //si no existe la tarea se le advierte al usuario y luego se elimina la tarea
        if (tareaestandar.getTitulo().equals("")) {
            JOptionPane.showMessageDialog(this, "La tarea con el nombre introducido no existe",
                        "Tarea no encontrada", JOptionPane.ERROR_MESSAGE);
        }
        //Recorremos todas las tareas en busca de la tarea "tareaestandar", una vez encontrado eliminamos de la lista 
        //de tareas del usuario la tarea "tareaestandar"
        for (Usuario u : dat.getUsuarios()) {
            if (u.getTareas().contains(tareaestandar)) {
                u.getTareas().remove(tareaestandar);
            }
        }
        for (Proyecto p : dat.getProyectos()) {
            if (p.getTareas().contains(tareaestandar)) {
                p.getTareas().remove(tareaestandar);
            }
        }
        
        
        dat.getTareas().remove(tareaestandar);
        Datos.guardarDatos(dat);
        campoNombreTarea.setText("");
    }//GEN-LAST:event_botonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JEliminarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JEliminarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JEliminarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JEliminarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JEliminarTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JTextField campoNombreTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
