package Proyecto;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Carri
 */
public class JEliminarTareaDeProyecto extends javax.swing.JFrame {

    /**
     * Creates new form JEliminarTareaDeProyecto
     */
    public JEliminarTareaDeProyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNombreProyecto = new javax.swing.JTextField();
        campoTítuloTarea = new javax.swing.JTextField();
        botonAñadirTarea = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 350, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar Tarea");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del proyecto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Título de la tarea:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        campoNombreProyecto.setBackground(new java.awt.Color(0, 102, 255));
        campoNombreProyecto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNombreProyecto.setForeground(new java.awt.Color(255, 255, 255));
        campoNombreProyecto.setBorder(null);
        jPanel1.add(campoNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 350, -1));

        campoTítuloTarea.setBackground(new java.awt.Color(0, 102, 255));
        campoTítuloTarea.setForeground(new java.awt.Color(255, 255, 255));
        campoTítuloTarea.setBorder(null);
        jPanel1.add(campoTítuloTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 350, -1));

        botonAñadirTarea.setText("Eliminar");
        botonAñadirTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirTareaActionPerformed(evt);
            }
        });
        jPanel1.add(botonAñadirTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirTareaActionPerformed
        //iniciamos variables que nos haran falta mas tarde
        String nombreproyecto = campoNombreProyecto.getText();
        String nombretarea = campoTítuloTarea.getText();

        Datos dat = Datos.cargarDatos();
        String fechaEstandar = "0001/01/01";
        //creamos un formateador de fecha para que sean legibles
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate FechaInicio = LocalDate.parse(fechaEstandar, formateador);
        //creamos una Tarea dummy y un boolean para saber si en el bucle se encuentra alguna coincidencia de titulo
        Tarea tareaestandar = new Tarea("", "", FechaInicio, FechaInicio, FechaInicio);
        boolean tareaencontrada = false;
        for (Tarea t : dat.getTareas()) {
            if (t.getTitulo().equalsIgnoreCase(nombretarea)) {
                tareaestandar = t;
                tareaencontrada = true;
            }
        }
        //sin no se encuentra ninguna coincidencia se utiliza la Trea dummy para mandar una alerta al usuario
        if (tareaestandar.getTitulo().equals("")) {
            JOptionPane.showMessageDialog(this, "La tarea con el titulo introducido no existe.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        //se cre un proyecto dummy y un boolean para saber si en el bucle se encuentra alguna coincidencia de nombre de proyecto
        Proyecto proyectoestandar = new Proyecto("", FechaInicio, FechaInicio);
        boolean proyectoencontrado = false;
        for (Proyecto p : dat.getProyectos()) {
            if (p.getNombre().equalsIgnoreCase(nombreproyecto)) {
                proyectoestandar = p;
                proyectoencontrado = true;
            }
        }
        //si no se encuentra ninguna coincidencia se utilizaz el proyecto dummy papra alertar al usuario
        if (proyectoestandar.getNombre().equals("")) {
            JOptionPane.showMessageDialog(this, "El proyecto con el titulo introducido no existe.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        //si en ambos bucles se encuentran una coincidencia procedemos a eliminar la tarea del proyecto en cuestion
        if(tareaencontrada && proyectoencontrado){
            proyectoestandar.elimninarTarea(tareaestandar);
            tareaestandar.setEnProyecto(false);
            JOptionPane.showMessageDialog(this, "Tarea eliminada con éxito.",
                    "Tarea eliminada.", JOptionPane.INFORMATION_MESSAGE);
        }
        
        Datos.guardarDatos(dat);
        campoNombreProyecto.setText("");
        campoTítuloTarea.setText("");
    }//GEN-LAST:event_botonAñadirTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JEliminarTareaDeProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JEliminarTareaDeProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JEliminarTareaDeProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JEliminarTareaDeProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JEliminarTareaDeProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirTarea;
    private javax.swing.JTextField campoNombreProyecto;
    private javax.swing.JTextField campoTítuloTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
