/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Carri
 */
public class JMostrarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form JMostrarUsuarios
     */
    public JMostrarUsuarios() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaGraficaUsuarios = new javax.swing.JList<>();
        botonMostrarUsuarios = new javax.swing.JButton();
        botonOrdenarPorNombreASC = new javax.swing.JButton();
        botonOrdenarPorNombreDEC = new javax.swing.JButton();
        botonOrdenarPorApellidosASC = new javax.swing.JButton();
        botonOrdenarPorApellidosDEC = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaGraficaUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(listaGraficaUsuarios);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 10, 630, 400));

        botonMostrarUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonMostrarUsuarios.setForeground(new java.awt.Color(51, 102, 255));
        botonMostrarUsuarios.setText("Mostrar  usuarios");
        botonMostrarUsuarios.setToolTipText("");
        botonMostrarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonMostrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 300, 50));

        botonOrdenarPorNombreASC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonOrdenarPorNombreASC.setText("Ordenar por nombre (ASC)");
        botonOrdenarPorNombreASC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarPorNombreASCActionPerformed(evt);
            }
        });
        jPanel1.add(botonOrdenarPorNombreASC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 300, 50));

        botonOrdenarPorNombreDEC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonOrdenarPorNombreDEC.setText("Ordenar por nombre (DEC)");
        botonOrdenarPorNombreDEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarPorNombreDECActionPerformed(evt);
            }
        });
        jPanel1.add(botonOrdenarPorNombreDEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, 50));

        botonOrdenarPorApellidosASC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonOrdenarPorApellidosASC.setText("Ordenar por apellidos (ASC)");
        botonOrdenarPorApellidosASC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarPorApellidosASCActionPerformed(evt);
            }
        });
        jPanel1.add(botonOrdenarPorApellidosASC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 300, 50));

        botonOrdenarPorApellidosDEC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonOrdenarPorApellidosDEC.setText("Ordenar por apellidos (DEC)");
        botonOrdenarPorApellidosDEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarPorApellidosDECActionPerformed(evt);
            }
        });
        jPanel1.add(botonOrdenarPorApellidosDEC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarUsuariosActionPerformed
        //cargar los datos para mostrarlos en una JLista por orden de creacion.
        Datos dat = Datos.cargarDatos();

        DefaultListModel modeloLista = new DefaultListModel();
        modeloLista.addAll(dat.getUsuarios());
        listaGraficaUsuarios.setModel(modeloLista);

    }//GEN-LAST:event_botonMostrarUsuariosActionPerformed

    private void botonOrdenarPorNombreASCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarPorNombreASCActionPerformed
        //cargar los datos para mostrarlos en una JLista por orden de Nombre ascendente.
        Datos dat = Datos.cargarDatos();

        DefaultListModel modeloLista = new DefaultListModel();
        Collections.sort(dat.getUsuarios(), (u1,u2) -> (u1.getNombre().compareToIgnoreCase(u2.getNombre())));
        modeloLista.addAll(dat.getUsuarios());
        listaGraficaUsuarios.setModel(modeloLista);
    }//GEN-LAST:event_botonOrdenarPorNombreASCActionPerformed

    private void botonOrdenarPorNombreDECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarPorNombreDECActionPerformed
        //cargar los datos para mostrarlos en una JLista por orden de Nombre descendente.
        Datos dat = Datos.cargarDatos();

        DefaultListModel modeloLista = new DefaultListModel();
        Collections.sort(dat.getUsuarios(), (u2,u1) -> (u1.getNombre().compareToIgnoreCase(u2.getNombre())));
        modeloLista.addAll(dat.getUsuarios());
        listaGraficaUsuarios.setModel(modeloLista);
    }//GEN-LAST:event_botonOrdenarPorNombreDECActionPerformed

    private void botonOrdenarPorApellidosASCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarPorApellidosASCActionPerformed
        //cargar los datos para mostrarlos en una JLista por orden de Apellidos ascendente.
        Datos dat = Datos.cargarDatos();

        DefaultListModel modeloLista = new DefaultListModel();
        Collections.sort(dat.getUsuarios(),Comparator.comparing(Usuario::getApellido1).thenComparing(Usuario::getApellido2));
        modeloLista.addAll(dat.getUsuarios());
        listaGraficaUsuarios.setModel(modeloLista);
    }//GEN-LAST:event_botonOrdenarPorApellidosASCActionPerformed

    private void botonOrdenarPorApellidosDECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarPorApellidosDECActionPerformed
        //cargar los datos para mostrarlos en una JLista por orden de Apellidos descendente.
        Datos dat = Datos.cargarDatos();

        DefaultListModel modeloLista = new DefaultListModel();
        Collections.sort(dat.getUsuarios(),Comparator.comparing(Usuario::getApellido1,Collections.reverseOrder()).thenComparing(Usuario::getApellido2));
        modeloLista.addAll(dat.getUsuarios());
        listaGraficaUsuarios.setModel(modeloLista);
    }//GEN-LAST:event_botonOrdenarPorApellidosDECActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMostrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMostrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMostrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMostrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMostrarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMostrarUsuarios;
    private javax.swing.JButton botonOrdenarPorApellidosASC;
    private javax.swing.JButton botonOrdenarPorApellidosDEC;
    private javax.swing.JButton botonOrdenarPorNombreASC;
    private javax.swing.JButton botonOrdenarPorNombreDEC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaGraficaUsuarios;
    // End of variables declaration//GEN-END:variables
}
