package Proyecto;


import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Carri
 */
public class JProyectos extends javax.swing.JFrame {
    private JFrame JAñadirTarea = new JAñadirTarea();
    private JFrame JCrearProyecto = new JCrearProyecto();
    private JFrame JEliminarTareaDeProyecto = new JEliminarTareaDeProyecto();
    private JFrame JMostrarTareasDeUnProyecto = new JMostrarTareasDeUnProyecto();
    private JFrame JMostrarProyectos = new JMostrarProyectos();
    private JFrame JEditarProyecto = new JEditarProyecto();
    private JFrame JEliminarProyecto = new JEliminarProyecto();
    /**
     * Creates new form JProyectos
     */
    public JProyectos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonMostrarTareas = new javax.swing.JButton();
        botonAñadirTarea = new javax.swing.JButton();
        botonEliminarProyecto = new javax.swing.JButton();
        botonCrearProyecto = new javax.swing.JButton();
        botonMostrarProyectos = new javax.swing.JButton();
        botonEditarProyecto = new javax.swing.JButton();
        botonEliminarTareaDeProyecto = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMostrarTareas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonMostrarTareas.setText("Mostrar Tareas");
        botonMostrarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTareasActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrarTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 300, 50));

        botonAñadirTarea.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonAñadirTarea.setText("Añadir Tarea");
        botonAñadirTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirTareaActionPerformed(evt);
            }
        });
        jPanel1.add(botonAñadirTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 300, 50));

        botonEliminarProyecto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonEliminarProyecto.setText("Eliminar proyecto");
        botonEliminarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProyectoActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 300, 50));

        botonCrearProyecto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonCrearProyecto.setText("Crear Proyecto");
        botonCrearProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearProyectoActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 50));

        botonMostrarProyectos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonMostrarProyectos.setText("Mostrar Proyectos");
        botonMostrarProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarProyectosActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrarProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 300, 50));

        botonEditarProyecto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonEditarProyecto.setText("Editar Proyecto");
        botonEditarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarProyectoActionPerformed(evt);
            }
        });
        jPanel1.add(botonEditarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 300, 50));

        botonEliminarTareaDeProyecto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonEliminarTareaDeProyecto.setText("Eliminar Tarea");
        botonEliminarTareaDeProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTareaDeProyectoActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminarTareaDeProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 300, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirTareaActionPerformed
        JAñadirTarea.setVisible(true);
    }//GEN-LAST:event_botonAñadirTareaActionPerformed

    private void botonCrearProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearProyectoActionPerformed
        JCrearProyecto.setVisible(true);
    }//GEN-LAST:event_botonCrearProyectoActionPerformed

    private void botonEliminarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProyectoActionPerformed
        JEliminarProyecto.setVisible(true);
    }//GEN-LAST:event_botonEliminarProyectoActionPerformed

    private void botonMostrarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTareasActionPerformed
        JMostrarTareasDeUnProyecto.setVisible(true);
    }//GEN-LAST:event_botonMostrarTareasActionPerformed

    private void botonMostrarProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarProyectosActionPerformed
        JMostrarProyectos.setVisible(true);
    }//GEN-LAST:event_botonMostrarProyectosActionPerformed

    private void botonEditarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarProyectoActionPerformed
        JEditarProyecto.setVisible(true);
    }//GEN-LAST:event_botonEditarProyectoActionPerformed

    private void botonEliminarTareaDeProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTareaDeProyectoActionPerformed
        JEliminarTareaDeProyecto.setVisible(true);
    }//GEN-LAST:event_botonEliminarTareaDeProyectoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JProyectos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirTarea;
    private javax.swing.JButton botonCrearProyecto;
    private javax.swing.JButton botonEditarProyecto;
    private javax.swing.JButton botonEliminarProyecto;
    private javax.swing.JButton botonEliminarTareaDeProyecto;
    private javax.swing.JButton botonMostrarProyectos;
    private javax.swing.JButton botonMostrarTareas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
