/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JFrame;

/**
 *
 * @author casto
 */
public class JTarea extends javax.swing.JFrame {
    
    private JFrame JEliminarTarea = new JEliminarTarea();
    private JFrame JAñadirUsuario = new JAñadirUsuario();
    private JFrame JMostrarTarea = new JMostrarTarea();
    private JFrame JBuscarTareasUsuario = new JBuscarTareasUsuario();
    private JFrame JMostrarProyecto = new JMostrarProyecto();
    private JFrame JBuscarTareaTitulo = new JBuscarTareaTitulo();
    private JFrame JCrearTarea = new JCrearTarea();
    private JFrame JEditarTarea = new JEditarTarea();

    /**
     * Creates new form JTarea
     */
    public JTarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonMostrarProyecto = new javax.swing.JButton();
        botonMostrarTareas = new javax.swing.JButton();
        botonEliminarTarea = new javax.swing.JButton();
        botonAñadirUsuario = new javax.swing.JButton();
        botonBuscarTareasUsuario = new javax.swing.JButton();
        botonBuscarTarea = new javax.swing.JButton();
        botonCrearTarea = new javax.swing.JButton();
        botonEditarTarea = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMostrarProyecto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonMostrarProyecto.setText("Mostrar proyecto de la tarea");
        botonMostrarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarProyectoActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 350, 50));

        botonMostrarTareas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonMostrarTareas.setText("Mostrar tareas");
        botonMostrarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTareasActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrarTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 350, 50));

        botonEliminarTarea.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonEliminarTarea.setText("Eliminar tarea");
        botonEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTareaActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 350, 50));

        botonAñadirUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonAñadirUsuario.setText("Añadir usuario");
        botonAñadirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonAñadirUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 350, 50));

        botonBuscarTareasUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonBuscarTareasUsuario.setText("Buscar tareas de un usuario");
        botonBuscarTareasUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarTareasUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarTareasUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 350, 50));

        botonBuscarTarea.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonBuscarTarea.setText("Buscar tarea por titulo");
        botonBuscarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarTareaActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 350, 50));

        botonCrearTarea.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonCrearTarea.setText("Crear tarea");
        botonCrearTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearTareaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 50));

        botonEditarTarea.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonEditarTarea.setText("Editar tarea");
        botonEditarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarTareaActionPerformed(evt);
            }
        });
        jPanel1.add(botonEditarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 350, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTareaActionPerformed
        JEliminarTarea.setVisible(true);
    }//GEN-LAST:event_botonEliminarTareaActionPerformed

    private void botonMostrarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarProyectoActionPerformed
        JMostrarProyecto.setVisible(true);
    }//GEN-LAST:event_botonMostrarProyectoActionPerformed

    private void botonMostrarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTareasActionPerformed
        JMostrarTarea.setVisible(true);
    }//GEN-LAST:event_botonMostrarTareasActionPerformed

    private void botonAñadirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirUsuarioActionPerformed
        JAñadirUsuario.setVisible(true);
    }//GEN-LAST:event_botonAñadirUsuarioActionPerformed

    private void botonBuscarTareasUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarTareasUsuarioActionPerformed
        JBuscarTareasUsuario.setVisible(true);
    }//GEN-LAST:event_botonBuscarTareasUsuarioActionPerformed

    private void botonBuscarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarTareaActionPerformed
        JBuscarTareaTitulo.setVisible(true);
    }//GEN-LAST:event_botonBuscarTareaActionPerformed

    private void botonCrearTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearTareaActionPerformed
        JCrearTarea.setVisible(true);
    }//GEN-LAST:event_botonCrearTareaActionPerformed

    private void botonEditarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarTareaActionPerformed
        JEditarTarea.setVisible(true);
    }//GEN-LAST:event_botonEditarTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirUsuario;
    private javax.swing.JButton botonBuscarTarea;
    private javax.swing.JButton botonBuscarTareasUsuario;
    private javax.swing.JButton botonCrearTarea;
    private javax.swing.JButton botonEditarTarea;
    private javax.swing.JButton botonEliminarTarea;
    private javax.swing.JButton botonMostrarProyecto;
    private javax.swing.JButton botonMostrarTareas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
