/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JFrame;

/**
 *
 * @author Carri
 */
public class JUsuario extends javax.swing.JFrame {
    private JFrame JCrearUsuarios = new JCrearUsuarios();
    private JFrame JeliminarUsuario = new JEliminarUsuario();
    private JFrame JBuscarUsuario = new JBuscarUsuario();
    private JFrame JBuscarTareasUsuario = new JBuscarTareasUsuario();
    private JFrame JEditarUsuario = new JEditarUsuario();
    private JFrame JMostrarUsuarios = new JMostrarUsuarios();
    /**
     * Creates new form JUsuario
     */
    public JUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonMostrarUsuarios = new javax.swing.JButton();
        botonBuscarTareas = new javax.swing.JButton();
        botonEditarUsuario = new javax.swing.JButton();
        botonCrearUsuario = new javax.swing.JButton();
        botonEliminarUsuario = new javax.swing.JButton();
        botonBuscarUsuario = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMostrarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonMostrarUsuarios.setText("Mostrar usuarios");
        botonMostrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(botonMostrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 300, 50));

        botonBuscarTareas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonBuscarTareas.setText("Buscar tareas del usuario");
        botonBuscarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarTareasActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 300, 50));

        botonEditarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonEditarUsuario.setText("Editar usuario");
        botonEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 300, 50));

        botonCrearUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonCrearUsuario.setText("Crear usuario");
        botonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 50));

        botonEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonEliminarUsuario.setText("Eliminar usuario");
        botonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 300, 50));

        botonBuscarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonBuscarUsuario.setText("Buscar usuario");
        botonBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 300, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarUsuarioActionPerformed
        JEditarUsuario.setVisible(true);
    }//GEN-LAST:event_botonEditarUsuarioActionPerformed

    private void botonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearUsuarioActionPerformed
        JCrearUsuarios.setVisible(true);
    }//GEN-LAST:event_botonCrearUsuarioActionPerformed

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        JeliminarUsuario.setVisible(true);
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    private void botonBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarUsuarioActionPerformed
        JBuscarUsuario.setVisible(true);
    }//GEN-LAST:event_botonBuscarUsuarioActionPerformed

    private void botonBuscarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarTareasActionPerformed
        JBuscarTareasUsuario.setVisible(true);
    }//GEN-LAST:event_botonBuscarTareasActionPerformed

    private void botonMostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarUsuariosActionPerformed
        JMostrarUsuarios.setVisible(true);
    }//GEN-LAST:event_botonMostrarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarTareas;
    private javax.swing.JButton botonBuscarUsuario;
    private javax.swing.JButton botonCrearUsuario;
    private javax.swing.JButton botonEditarUsuario;
    private javax.swing.JButton botonEliminarUsuario;
    private javax.swing.JButton botonMostrarUsuarios;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
